# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric properties
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.18.4
loom_version=1.15.4
fabric_version=0.119.4+1.21.4
fabric_kotlin_version=1.13.9+kotlin.2.3.10
kotlin_version=2.3.10

# Mod properties
mod_version=0.1.0
maven_group=gg.flyte.pluginportal.e2e
archives_base_name=plugin-portal-e2e-client
